// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuizProject.Data;

#nullable disable

namespace QuizProject.Migrations
{
    [DbContext(typeof(QuizContext))]
    [Migration("20240902130543_Configures tables and records added")]
    partial class Configurestablesandrecordsadded
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("QuizProject.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CategoryName = "Nature"
                        },
                        new
                        {
                            CategoryId = 2,
                            CategoryName = "Sports"
                        },
                        new
                        {
                            CategoryId = 3,
                            CategoryName = "Movies"
                        },
                        new
                        {
                            CategoryId = 4,
                            CategoryName = "Technology"
                        },
                        new
                        {
                            CategoryId = 5,
                            CategoryName = "Music"
                        });
                });

            modelBuilder.Entity("QuizProject.Models.Player", b =>
                {
                    b.Property<int>("PlayerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PlayerId"));

                    b.Property<string>("PlayerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PlayerId");

                    b.ToTable("Players");

                    b.HasData(
                        new
                        {
                            PlayerId = 1,
                            PlayerName = "Salva"
                        },
                        new
                        {
                            PlayerId = 2,
                            PlayerName = "Toto"
                        },
                        new
                        {
                            PlayerId = 3,
                            PlayerName = "Velsal"
                        });
                });

            modelBuilder.Entity("QuizProject.Models.Question", b =>
                {
                    b.Property<int>("QuestionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("QuestionId"));

                    b.Property<string>("Answer1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Answer2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Answer3")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Answer4")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("CorrectAnswer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QuestionText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("QuestionId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Questions");

                    b.HasData(
                        new
                        {
                            QuestionId = 1,
                            Answer1 = "Nectar",
                            Answer2 = "Yeast",
                            Answer3 = "Eggs",
                            Answer4 = "Self-Rising Flour",
                            CategoryId = 1,
                            CorrectAnswer = "Nectar",
                            QuestionText = "What do bees gather in order to make honey?"
                        },
                        new
                        {
                            QuestionId = 2,
                            Answer1 = "Milligram",
                            Answer2 = "Millipede",
                            Answer3 = "Millisecond",
                            Answer4 = "Millimetre",
                            CategoryId = 1,
                            CorrectAnswer = "Millipede",
                            QuestionText = "Which of those is a creature with many legs?"
                        },
                        new
                        {
                            QuestionId = 3,
                            Answer1 = "Hailstone",
                            Answer2 = "Eclipse",
                            Answer3 = "Rainbow",
                            Answer4 = "Sunbeam",
                            CategoryId = 1,
                            CorrectAnswer = "Rainbow",
                            QuestionText = "Which natural phenomenon is a display of the visible spectrum?"
                        },
                        new
                        {
                            QuestionId = 4,
                            Answer1 = "The Scoville Scale",
                            Answer2 = "The Fujita Scale",
                            Answer3 = "The Borg Scale",
                            Answer4 = "The Richter Scale",
                            CategoryId = 1,
                            CorrectAnswer = "The Richter Scale",
                            QuestionText = "What scale is used to measure earthquakes?"
                        },
                        new
                        {
                            QuestionId = 5,
                            Answer1 = "The Elephant",
                            Answer2 = "The Cow",
                            Answer3 = "The Kangaroo",
                            Answer4 = "The Fox",
                            CategoryId = 1,
                            CorrectAnswer = "The Elephant",
                            QuestionText = "Which of those mammals can't jump?"
                        },
                        new
                        {
                            QuestionId = 6,
                            Answer1 = "Football",
                            Answer2 = "Baseball",
                            Answer3 = "Hockey",
                            Answer4 = "Basketball",
                            CategoryId = 2,
                            CorrectAnswer = "Baseball",
                            QuestionText = "In which sport can you hit a \"Home Run\"?"
                        },
                        new
                        {
                            QuestionId = 7,
                            Answer1 = "Shot pitch",
                            Answer2 = "Shot toss",
                            Answer3 = "Shot put",
                            Answer4 = "Shot set",
                            CategoryId = 2,
                            CorrectAnswer = "Shot put",
                            QuestionText = "Which of these is an Olympic field event?"
                        },
                        new
                        {
                            QuestionId = 8,
                            Answer1 = "US Open",
                            Answer2 = "NBA All-Star Game",
                            Answer3 = "Super Bowl",
                            Answer4 = "Indianapolis 500",
                            CategoryId = 2,
                            CorrectAnswer = "Indianapolis 500",
                            QuestionText = "Which of these events takes place in the Brickyard?"
                        },
                        new
                        {
                            QuestionId = 9,
                            Answer1 = "Billiards",
                            Answer2 = "Tennis",
                            Answer3 = "Football",
                            Answer4 = "Hockey",
                            CategoryId = 2,
                            CorrectAnswer = "Billiards",
                            QuestionText = "In which of these sports would you use a cue to hit the ball?"
                        },
                        new
                        {
                            QuestionId = 10,
                            Answer1 = "Triple jump",
                            Answer2 = "Ski jumping",
                            Answer3 = "Curling",
                            Answer4 = "Rifle Shooting",
                            CategoryId = 2,
                            CorrectAnswer = "Ski jumping",
                            QuestionText = "The \"K-Point\" is a measurement used in which sport?"
                        },
                        new
                        {
                            QuestionId = 11,
                            Answer1 = "A Lion",
                            Answer2 = "A Dinosaur",
                            Answer3 = "An Ape",
                            Answer4 = "A Lizard",
                            CategoryId = 3,
                            CorrectAnswer = "An Ape",
                            QuestionText = "What type of animal is King Kong n the film of the same name?"
                        },
                        new
                        {
                            QuestionId = 12,
                            Answer1 = "Northwood",
                            Answer2 = "Southwood",
                            Answer3 = "Eastwood",
                            Answer4 = "Westwood",
                            CategoryId = 3,
                            CorrectAnswer = "Eastwood",
                            QuestionText = "Which of these is a famous Hollywood actor?"
                        },
                        new
                        {
                            QuestionId = 13,
                            Answer1 = "Dean Green",
                            Answer2 = "Lou Blue",
                            Answer3 = "Jay Green",
                            Answer4 = "Jack Black",
                            CategoryId = 3,
                            CorrectAnswer = "Jack Black",
                            QuestionText = "Who starred in the 2003 comedy \"School of Rock\"?"
                        },
                        new
                        {
                            QuestionId = 14,
                            Answer1 = "Christian Bale",
                            Answer2 = "Jake Gyllenhaal",
                            Answer3 = "Wes Bentley",
                            Answer4 = "Mark Wahlberg",
                            CategoryId = 3,
                            CorrectAnswer = "Christian Bale",
                            QuestionText = "Which actor played the title role in Batman Begins, reseased in 2005?"
                        },
                        new
                        {
                            QuestionId = 15,
                            Answer1 = "Conrad Veidt",
                            Answer2 = "Werner Krauss",
                            Answer3 = "Friedrich Feher",
                            Answer4 = "Lil Dagover",
                            CategoryId = 3,
                            CorrectAnswer = "Werner Krauss",
                            QuestionText = "Which actor played the role of Doctor Caligari in the 1920 movie \"The Cabinet of Dr. Caligari\"?"
                        },
                        new
                        {
                            QuestionId = 16,
                            Answer1 = "Panasonic",
                            Answer2 = "Hitachi",
                            Answer3 = "Sony",
                            Answer4 = "Casio",
                            CategoryId = 4,
                            CorrectAnswer = "Sony",
                            QuestionText = "Which company created the first portable CD player known as the Discman?"
                        },
                        new
                        {
                            QuestionId = 17,
                            Answer1 = "2000",
                            Answer2 = "2007",
                            Answer3 = "2010",
                            Answer4 = "2020",
                            CategoryId = 4,
                            CorrectAnswer = "2007",
                            QuestionText = "When was the first iPhone released?"
                        },
                        new
                        {
                            QuestionId = 18,
                            Answer1 = "James Gosling",
                            Answer2 = "Ted Codd",
                            Answer3 = "Larry Ellison",
                            Answer4 = "Tim Berners-Lee",
                            CategoryId = 4,
                            CorrectAnswer = "Tim Berners-Lee",
                            QuestionText = "Who is the inventor of the \"World Wide Web\"?"
                        },
                        new
                        {
                            QuestionId = 19,
                            Answer1 = "Volkswagen",
                            Answer2 = "Audi",
                            Answer3 = "BMW",
                            Answer4 = "Mercedes",
                            CategoryId = 4,
                            CorrectAnswer = "Volkswagen",
                            QuestionText = "Which car company manufactures the Passat?"
                        },
                        new
                        {
                            QuestionId = 20,
                            Answer1 = "Pac-Man",
                            Answer2 = "Pong",
                            Answer3 = "Space Invaders",
                            Answer4 = "Jumpman",
                            CategoryId = 4,
                            CorrectAnswer = "Pong",
                            QuestionText = "What is the first arcade video game?"
                        },
                        new
                        {
                            QuestionId = 21,
                            Answer1 = "Duke Ellington",
                            Answer2 = "Count Basie",
                            Answer3 = "Cab Calloway",
                            Answer4 = "Benny Goodman",
                            CategoryId = 5,
                            CorrectAnswer = "Cab Calloway",
                            QuestionText = "Who made the jazz standard \"Minnie the Moocher\"?"
                        },
                        new
                        {
                            QuestionId = 22,
                            Answer1 = "\"Baby Shark\" by Pinkfong",
                            Answer2 = "\"Despacito\" by Luis Fonsi",
                            Answer3 = "\"Uptown Funk\" by Mark Ronson",
                            Answer4 = "\"Gangnam Style\"  by Psy",
                            CategoryId = 5,
                            CorrectAnswer = "\"Gangnam Style\"  by Psy",
                            QuestionText = "What music video was the first video to reach 1 billion views?"
                        },
                        new
                        {
                            QuestionId = 23,
                            Answer1 = "Nas",
                            Answer2 = "Dr. Dre",
                            Answer3 = "Snoop Dogg",
                            Answer4 = "50 Cent",
                            CategoryId = 5,
                            CorrectAnswer = "Nas",
                            QuestionText = "Who released the iconic debut album \"Illmatic\" in 1994?"
                        },
                        new
                        {
                            QuestionId = 24,
                            Answer1 = "Prince",
                            Answer2 = "Michael Jackson",
                            Answer3 = "Lionel Richie",
                            Answer4 = "Phil Collins",
                            CategoryId = 5,
                            CorrectAnswer = "Michael Jackson",
                            QuestionText = "Who is known as the \"King of Pop\"?"
                        },
                        new
                        {
                            QuestionId = 25,
                            Answer1 = "Bleach",
                            Answer2 = "Nevermind",
                            Answer3 = "The Colour and the Shape",
                            Answer4 = "In Utero",
                            CategoryId = 5,
                            CorrectAnswer = "The Colour and the Shape",
                            QuestionText = "Which of these albums was not released by the band \"Nirvana\"?"
                        });
                });

            modelBuilder.Entity("QuizProject.Models.Score", b =>
                {
                    b.Property<int>("ScoreId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ScoreId"));

                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.Property<int>("ScoreCount")
                        .HasColumnType("int");

                    b.HasKey("ScoreId");

                    b.HasIndex("PlayerId");

                    b.ToTable("Scores");

                    b.HasData(
                        new
                        {
                            ScoreId = 1,
                            PlayerId = 1,
                            ScoreCount = 4
                        },
                        new
                        {
                            ScoreId = 2,
                            PlayerId = 2,
                            ScoreCount = 8
                        },
                        new
                        {
                            ScoreId = 3,
                            PlayerId = 3,
                            ScoreCount = 12
                        },
                        new
                        {
                            ScoreId = 4,
                            PlayerId = 1,
                            ScoreCount = 2
                        },
                        new
                        {
                            ScoreId = 5,
                            PlayerId = 2,
                            ScoreCount = 6
                        },
                        new
                        {
                            ScoreId = 6,
                            PlayerId = 3,
                            ScoreCount = 10
                        });
                });

            modelBuilder.Entity("QuizProject.Models.Question", b =>
                {
                    b.HasOne("QuizProject.Models.Category", "Category")
                        .WithMany("Questions")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("QuizProject.Models.Score", b =>
                {
                    b.HasOne("QuizProject.Models.Player", "Player")
                        .WithMany("Scores")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("QuizProject.Models.Category", b =>
                {
                    b.Navigation("Questions");
                });

            modelBuilder.Entity("QuizProject.Models.Player", b =>
                {
                    b.Navigation("Scores");
                });
#pragma warning restore 612, 618
        }
    }
}
